### ISSUE TITLE
Feature Request: Add option to install Linux-TKG kernels.

### ISSUE THREAD

**Issue by Abdulsarhan** [CachyOS/kernel-manager#10]
Hello, I know that this is not an issue but I did not know where I could submit requests for this sort of thing. 

But yeah, I would like to be able to install this kernel using the kernel manager because it provides really good performance for gaming. 

[linux-tkg](https://github.com/Frogging-Family/linux-tkg#linux-tkg)

**Comment by ptr1337** [comment]
This wont happen, due its problematic buildsystem.
If TKG ever creates a github repo for the CI Kernel, but currently the build system works very bad for repository management. Also the reason why chaotic-aur dropped the kernels.

There does not seem a proper interest to fix these issues and there was multiple times said, that linux-tkg is only thought to be selfbuilt from the user.

The kernel manager does provide prebuilts for all linux-cachyos variant including a own configureable kernel.
