### ISSUE TITLE
Newly compiled kernel not installed, cached is installed instead

### ISSUE THREAD

**Issue by spaceman7777** [CachyOS/kernel-manager#20]
Hi, I've been enjoying the cachy kernel manager recently, and have run into a bit of trouble.

So, the sequence of events is:
1. installed cachy at 6.10.6-2 kernel
2. compiled and installed the cachy kernel from the kernel manager at 6.10.6-2 version
3. my package manager alerted me to the release of 6.10.6-3
4. i upgraded to 6.10.6-3
5. i went to the kernel manager to recompile, and it says that it indeed knows about the 6.10.6-3 kernel, it indeed did compile it, but when it goes to install it, my package manager alerts me that I'm in fact downgrading to 6.10.6-2

It seems as though the install step is picking up on some previously cached and compiled version of the kernel.

For the sake of simplicity and brevity, I cut out a variety of troubleshooting steps I had taken in the middle. But those are the general reproduction steps that lead to the system being in this state. I am currently using the 1.9.1-1 release of kernel-manager

**Comment by vnepogodin** [comment]
That happens primarily due we having higher pkgrel version in repos, while in linux-cachyos repo pkgbuilds with lower pkgrel than compiled in repos

**Comment by ptr1337** [comment]
Would setting a custom-$pkgbase as default fine for you?

Like, just name it for example as default: linux-cachyos-custom or equal.

**Comment by spaceman7777** [comment]
Actually, this looks like it may be caused by a version mismatch between the cachyos-v3 and cachyos repositories.

After running a `paru -Ss linux-cachyos`, I noticed these two entries:
```
cachyos/linux-cachyos 6.10.6-2 [140.61 MiB 140.82 MiB] [Installed: 6.10.6-3]
    The Linux SCHED-EXT + BORE + Cachy Sauce Kernel by CachyOS with other patches and improvements
    kernel and modules
```
and 
```
cachyos-v3/linux-cachyos 6.10.6-3 [0 B 140.86 MiB] [Installed]
    The Linux SCHED-EXT + BORE + Cachy Sauce Kernel by CachyOS with other patches and improvements
    kernel and modules
```

(The part of note here is that linux-cachyos in v3 is 6.10.6-3, whereas it is 6.10.6-2 in the regular repository. Notably, all of the other linux-cachyos-* packages also appear to be 6.10.6-2.)

So, I assume this is just a factor of kernel manager pulling from the lower (normal) version number. Not sure what's up with the v3 repo, but it'll probably all straighten out in the end (or the compiled version in the cachyos repo can be upgraded, at least nominally, to 6.10.6-3)

**Comment by ptr1337** [comment]
Yes, that is because we need in cachyos-v3/v4/znver4 a higher pkgrel, since otherwise we will get at the installation of CachyOS a module mismatch, which is really not intended.

For the kernel manager, we will likely put a custom pkgbase as default, to avoid these issues.

**Comment by spaceman7777** [comment]
By the way, this seems to be resolved after updating to the new version of kernel manager, so it's all good :+1:
