### ISSUE TITLE
Fix password prompt delay to install the built kernel (if you leave the screen everthing is deleted).

### ISSUE THREAD

**Issue by Mangoes** [CachyOS/kernel-manager#7]
Hi,

If you leave the screen during the build and you are not fast enough to type the password after the build has completed, everything is canceled, the build folder is deleted and you are left with the "Press enter to exit" the shell. -> you have to start the complete kernel download & build again.

Could you remove this password expiration delay of find a way for this not to happen?

Thanks.

Btw, kernel-manager is an awesome tool!

**Comment by zakack** [comment]
If you miss that prompt the pkg is still preserved in ~/.cache/cachyos-km/pkgbuilds . And agreed, thanks everyone! This is an excellent tool.
